version: '2.2'
services:
  stubbyd:
    build:
      context: ./stubby
    restart: always
#    restart: on-failure
    # ports:
    #   - "53:53/udp"
  openvpn_server:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn:2.4
    # build:
    #     context: ./
    #     dockerfile: openvpn-server.dockerfile
    volumes:
      - /home/ubuntu/openvpndata:/etc/openvpn
    shm_size: 1G
    environment:
      # - EASYRSA_KEY_SIZE=3072
      - EASYRSA_KEY_SIZE=4096
      - EASYRSA_ALGO=ec
      - EASYRSA_CURVE=secp521r1
    depends_on:
      -  stubbyd
    links:
      -  stubbyd
    restart: always
#    restart: on-failure
    ports:
      - "1194:1194/udp"


# docker-compose run --rm openvpn_server ovpn_genconfig -u udp://VPN.SERVERNAME.COM
# docker-compose run --rm openvpn_server ovpn_initpki
# docker-compose run --rm openvpn_server easyrsa build-client-full xxx nopass
# docker-compose run --rm openvpn_server ovpn_getclient xxx > xxx.ovpn
