version: '2.2'
services:
  stubbyd:
    logging:
      options:
        max-size: 100m
    build:
      context: ./stubby
    networks:
      opv-stubby-net:
        ipv4_address: 172.30.0.2
    restart: always
    # ports:
    #   - "53:53/udp"
  openvpn_server:
    logging:
      options:
        max-size: 100m
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn:latest
    # build:
    #     context: ./
    #     dockerfile: openvpn-server.dockerfile
    volumes:
      - /home/ubuntu/openvpndata:/etc/openvpn
    shm_size: 1G
    environment:
      - EASYRSA_KEY_SIZE=4096
      - EASYRSA_DIGEST=sha512
      - EASYRSA_ALGO=ec
      - EASYRSA_CURVE=secp521r1
    networks:
      opv-stubby-net:
        ipv4_address: 172.30.0.3
    restart: always
    ports:
      - "1194:1194/udp"

networks:
  opv-stubby-net:
    ipam:
      config:
        - subnet: 172.30.0.0/24

# docker-compose run --rm openvpn_server ovpn_genconfig -u udp://VPN.SERVERNAME.COM
# docker-compose run --rm openvpn_server ovpn_initpki
# docker-compose run --rm openvpn_server easyrsa build-client-full xxx nopass
# docker-compose run --rm openvpn_server ovpn_getclient xxx > xxx.ovpn
