FROM ubuntu:20.04

RUN apt-get update
# https://stackoverflow.com/questions/58338266/curl-certificate-fail-in-docker-container
RUN apt-get install -y stubby ca-certificates dnsutils net-tools nano

COPY stubby.yml /etc/stubby/

ENTRYPOINT ["/usr/bin/stubby","-l"]
